import os
import sys
import asyncio
import json
import logging
import argparse
from dotenv import load_dotenv

# Ensure the console can render Unicode characters (✓ ✗ — etc.)
# on Windows terminals that default to cp1252.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Bootstrap local environment secrets from the .env file
load_dotenv()

from core import LLMModelFactory, LLMModelConfig
from proximity_metric import calculate_proximity_metrics

# Setup clean, structured telemetry logging format
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

def parse_command_line_arguments():
    """Parses incoming terminal flags into typed configuration parameters."""
    parser = argparse.ArgumentParser(
        description="Enterprise Multi-LLM Factory CLI Execution Utility",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument(
        "-p", "--provider",
        type=str,
        default=None,
        choices=["openai", "google", "aws_bedrock"],
        help="Target cloud interface provider infrastructure mapping (required unless -r is used)"
    )
    
    parser.add_argument(
        "-m", "--model",
        type=str,
        default=None,
        help="Target model deployment identifier string (e.g., 'gpt-4o', 'gemini-2.5-flash') (required unless -r is used)"
    )
    
    parser.add_argument(
        "-t", "--temperature",
        type=float,
        default=0.0,
        help="Sampling temperature constraint modifier bound between 0.0 and 2.0"
    )
    
    parser.add_argument(
        "-f", "--prompt-file",
        type=str,
        default=None,
        help="Optional path to a local text file (.txt) containing the execution prompt payload"
    )

    parser.add_argument(
        "-o", "--output-file",
        type=str,
        default="output.txt",
        help="Target local path to save the generated text payload response"
    )

    parser.add_argument(
        "-k", "--max-tokens",
        type=int,
        default=16384,  # Bumping the default terminal fallback to 4096
        help="Upper bound token allocation ceiling for the model response"
    )
    
    parser.add_argument(
        "-r", "--reasoning-file",
        type=str,
        default=None,
        help="Optional path to a text file (.txt) containing a pre-captured reasoning trace "
             "to analyse directly. When supplied, the LLM call is skipped entirely and "
             "proximity metrics are computed straight from the file content."
    )

    parser.add_argument(
        "-b", "--thinking-budget",
        type=int,
        default=None,
        help="Thinking token budget for Google Gemini 2.5+ models (default: 8192). "
             "Set to 0 to disable thinking. Higher values produce richer reasoning traces."
    )

    return parser.parse_args()

def process_reasoning_data(reasoning_text: str):
    """
    Prints the raw reasoning trace and runs the Topic-Aware Self-Correction
    Proximity pipeline, displaying structured uncertainty-resolution metrics.
    """
    if not reasoning_text:
        print("\n[System] No internal reasoning chain was generated by this model.")
        print("         Tip: For Gemini 2.5 models use -b/--thinking-budget (e.g. -b 8192)")
        print("              to guarantee thinking tokens are produced.\n")
        return

    # ── Raw reasoning trace ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("RAW REASONING TRACE")
    print("=" * 60)
    print(reasoning_text)
    print("=" * 60 + "\n")

    print("\n" + "=" * 60)
    print("PROXIMITY METRIC — UNCERTAINTY QUANTIFICATION")
    print("=" * 60)

    metrics = calculate_proximity_metrics(reasoning_text)

    # ── High-level summary ────────────────────────────────────────
    print(f"  Total hedges     : {metrics['total_hedges']}")
    print(f"  Resolved hedges  : {metrics['resolved_hedges']}")
    print(f"  Unresolved hedges: {metrics['unresolved_hedges']}")
    print(f"  TRUR             : {metrics['trur']:.2%}")
    print(f"  Weighted TRUR    : {metrics['weighted_trur']:.2%}")

    # ── Per-hedge detail ──────────────────────────────────────────
    if metrics["matches"]:
        print("\n  Per-hedge breakdown:")
        for m in metrics["matches"]:
            status = "✓ RESOLVED" if m["resolved"] else "✗ unresolved"
            print(f"\n    [{m['id']}] {status}")
            print(f"      Sentence         : {m['sentence']}")
            print(f"      Hedge keyword    : \"{m['matched_keyword']}\"")
            print(f"      Subject          : {m['subject']}")
            print(f"      Position         : sentence {m['position']}")
            if m["matched_verification"]:
                print(f"      Matched verif.   : {m['matched_verification']}")
                print(f"      Subject sim.     : {m['subject_similarity']:.4f}")
                print(f"      Proximity score  : {m['proximity_score']:.4f}")
                print(f"      Match score      : {m['match_score']:.4f}")
            print(f"      Effective weight : {m['effective_weight']:.4f}")

    # ── Full JSON output ──────────────────────────────────────────
    print("\n  Full JSON result:")
    print(json.dumps(metrics, indent=4))
    print("=" * 60 + "\n")

async def main():
    # 1. Capture user inputs from the terminal command execution
    args = parse_command_line_arguments()

    # ── MODE A: Direct reasoning-file analysis (no LLM call) ─────────────────
    if args.reasoning_file:
        print(f"\n=== Proximity Metric — Direct Reasoning File Analysis ===")
        print(f"Reasoning File  : {args.reasoning_file}")

        try:
            if not os.path.exists(args.reasoning_file):
                raise FileNotFoundError(
                    f"Reasoning file not found: '{args.reasoning_file}'"
                )
            with open(args.reasoning_file, "r", encoding="utf-8") as fh:
                reasoning_text = fh.read().strip()
            if not reasoning_text:
                raise ValueError(
                    f"Reasoning file '{args.reasoning_file}' is completely empty."
                )

            print(f"Characters read : {len(reasoning_text):,}\n")
            process_reasoning_data(reasoning_text)

        except FileNotFoundError as fnf_err:
            logging.error(f"File IO error: {fnf_err}")
        except ValueError as val_err:
            # Only catch ValueError raised by our own validation above,
            # not encoding errors bubbling up from process_reasoning_data.
            logging.error(f"Validation error: {val_err}")
        except Exception as runtime_err:
            logging.error(f"Analysis failed: {runtime_err}")
        return   # stop here — no LLM pipeline needed

    # ── MODE B: LLM call + automatic reasoning analysis ───────────────────────
    # -p and -m are required when not using -r; enforce manually so the error
    # message stays helpful even though argparse treats them as optional.
    if not args.provider or not args.model:
        logging.error(
            "--provider (-p) and --model (-m) are required unless "
            "--reasoning-file (-r) is supplied."
        )
        return

    print(f"\n=== Initializing Engine Connection Framework ===")
    print(f"Targeting Provider : {args.provider}")
    print(f"Targeting Model ID : {args.model}")
    print(f"Setting Temperature: {args.temperature}")
    print(f"Saving Output To   : {args.output_file}")
    if args.prompt_file:
        print(f"Reading Prompt From: {args.prompt_file}\n")
    else:
        print("Reading Prompt From: Default Fallback Context\n")

    try:
        # 2. Resolve prompt text from file or fall back to system default
        if args.prompt_file:
            if not os.path.exists(args.prompt_file):
                raise FileNotFoundError(f"The specified prompt file target was not found: '{args.prompt_file}'")
            
            with open(args.prompt_file, "r", encoding="utf-8") as file_stream:
                prompt_text = file_stream.read().strip()
                
            if not prompt_text:
                raise ValueError(f"The prompt file '{args.prompt_file}' is completely empty.")
        else:
            # High-level developer fallback default if the optional flag is omitted
            prompt_text = "Explain the core benefit of the Strategy Design Pattern in exactly two sentences."

        # 3. Package parsed CLI parameters straight into the Pydantic validator model
        config = LLMModelConfig(
            provider=args.provider,
            model_id=args.model,
            temperature=args.temperature,
            thinking_budget=args.thinking_budget,   # None = auto (8192 for gemini-2.5+)
        )

        # 4. Request appropriate driver routing client from the Factory layer
        client = LLMModelFactory.create_client(config)

        print(f"Resolved Prompt Payload:\n\"\"\"\n{prompt_text}\n\"\"\"\n")
        print("Waiting for cloud API runtime return state...")
        
        # 5. Trigger the target execution pipeline asynchronously
        response = await client.agenerate(prompt=prompt_text)

        # 6. Output response metrics and telemetry back to terminal screen
        print("\n----------------- EXECUTION COMPLETED SUCCESSFULLY -----------------")
        print(f"Raw Output Text Content:\n{response.content}")
        print(f"\nExecution Footprint Metadata Tracker:\n{response.metrics.model_dump()}")
        print("--------------------------------------------------------------------")

        # 3. Route the reasoning trace through the proximity metric pipeline
        process_reasoning_data(response.reasoning_content)

        # 7. Write the model response content payload to the designated output target
        with open(args.output_file, "w", encoding="utf-8") as output_stream:
            output_stream.write(response.content)
        print(f"📝 Output successfully tracked and written to: '{args.output_file}'\n")

    except FileNotFoundError as fnf_err:
        logging.error(f"File IO targeted route error: {fnf_err}")
    except ValueError as val_err:
        logging.error(f"Configuration parameter mapping validation error: {val_err}")
    except Exception as runtime_err:
        logging.error(f"A catastrophic pipeline execution failure occurred: {runtime_err}")

if __name__ == "__main__":
    # Standard terminal application execution runtime container entry point
    asyncio.run(main())